spring:
  profiles:
    active:
    - local-was
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always
server:
  port: 9080

---
spring:
  config:
    activate:
      on-profile: local-was
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
  h2:
    console:
      enabled: true
