spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      driver-class-name: org.h2.Driver
      username: sa
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 9080